export const metadata = {
  title: "All Pokemons",
  description: "Generated by create next app",
};

export default function AllPokemonsLayout({ children }) {
  return (
    <section>{children}</section>
  );
}
