import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pokemon Data",
  description: "Generated by create next app",
};

export default function PokemonDataLayout({ children }) {
  return (
    <section>{children}</section>
  );
}
