import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>{children}
        <footer className="mt-auto">
          <Footer/>
        </footer>
      </body>
      <Script src="https://kit.fontawesome.com/52afc80947.js"/>
    </html>
  );
}
